language: python
python:
  - "2.7.13"
  

install:
<<<<<<< HEAD
  - pip install django
  - pip install
  - pip install -U googlemaps
=======
  - pip install -r requirements.txt
>>>>>>> master

script: python manage.py test
